name: stock_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - pandas==2.2.2
    - ipykernel==6.16.2
    - scikit-learn==1.4.2
    - seaborn==0.13.2
    - tensorflow==2.16.1
    - mdpdf==0.0.18
    - xgboost==2.0.3

